#!/data/data/com.termux/files/usr/bin/env bash

# Alyx's TUR by Alyx Shang.
# Licensed under the FSL v1.

EXECNAME="sharkey"
TAG="v.0.2.0"
APPNAME="sharkey.rs"

build(){
    wget https://github.com/alyxshang/$APPNAME/archive/refs/tags/$TAG.tar.gz
    tar -xvzf $TAG.tar.gz
    cd $APPNAME-$TAG
    pwd
    cargo build --release --features=cli
    mv target/release/$EXECNAME .
}

install(){
    mv $EXECNAME $PREFIX/bin
}


clean(){
    cd ..
    rm -rf $TAG.tar.gz
    rm -rf $APPNAME-$TAG
}

main(){
    build
    #install
    clean
}

main