#!/data/data/com.termux/files/usr/bin/env bash

EXECNAME="luhny"
TAG="v.0.1.0"
APPNAME="luhny.rs"

build(){
    wget https://github.com/alyxshang/$APPNAME/archive/refs/tags/$TAG.tar.gz
    tar -xvzf $TAG.tar.gz
    cd $APPNAME-$TAG
    cargo build --release
    mv target/release/$EXECNAME .
}

install(){
    mv $EXECNAME $PREFIX/bin
}

clean(){
    cd ..
    rm -rf $TAG.tar.gz
    rm -rf $APPNAME-$TAG
}

main(){
    build
    install
    clean
}

main