name: TUR CI
on:
  push:
    branches: [ main ]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: "Install dependencies."
        run: |
            sudo apt update
            sudo apt upgrade -y
            sudo apt install -y python3 wget
      - name: "Verify the installation."
        run: python3 --version && wget --help
      - name: "Build package repository."
        run: bash build.sh && ls
      - name: "Deploy the repository."
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: dist