on: [push]
name: Sharkey Notifs
env:
  BLAHAJ_API_TOKEN: ${{ secrets.BLAHAJ_API_TOKEN }}
  MSG: "CI from commit https://github.com/${{ github.repository }}/commit/${{ github.sha }} succeeded."
jobs:
  build_and_test:
    name: Sharkey.rs CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      
      - name: "Install the Sharkey binary."
        id: "build"
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --git https://github.com/alyxshang/sharkey.rs --tag v.0.2.0 --features=cli
          
      - name: "Echo a message."
        run: echo $MSG
